#
# This file MUST be in UTF-8 format otherwise svls will not be able to load it.  Note that svlint --example
# will create a UTF16-BOM file under Windows Powershell 7.0 which has to be converted.
#

[Options]
exclude_paths = []
indent = 2
prefix_inout = "b_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u_"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "ifc_"

[rules]
prefix_module = true
prefix_inout = true
prefix_input = true
prefix_instance = true
prefix_interface = true
prefix_output = true
prefix_package = true